複数文字列検索(AhoCorasick)
habara-k/ICPCLibrary pull request #74
Opened 2020-10-27 07:21 UTC by habara-k

2020-11-02 18:33 UTC, kanra824 requested changes

2020-11-03 04:24 UTC, habara-k commented on lib/string/aho_corasick.cpp
> + * AhoCorasick PMA(26,'a');
`AhoCorasick<26,'a'> PMA;`ですね

2020-11-03 04:24 UTC, habara-k commented on lib/string/aho_corasick.cpp
> + * int now = root;
はい...

2020-11-03 04:24 UTC, habara-k commented on lib/string/aho_corasick.cpp
> + *     // ここでPMA.nodes[now].acceptとかを利用していろいろやる
そうです

2020-11-03 15:48 UTC, kanra824 commented
acceptの値って必ず0か1になると思うんだけど、intで持ってる理由ってありますか？（そのままでいいとは思うけど、使うときにちょっと混乱したので確認）

2020-11-03 15:48 UTC, kanra824 commented
それ以外は大丈夫そうです

2020-11-03 16:34 UTC, habara-k commented
> acceptの値って必ず0か1になると思うんだけど、intで持ってる理由ってありますか？（そのままでいいとは思うけど、使うときにちょっと混乱したので確認）

```
void add(const string& s, int id = 0)
```
でidを指定するんだけど、このid別にacceptが集計されるって感じ

idを毎回別の値にしたらacceptは0か1しか取らない

2020-11-03 16:34 UTC, merged